<a href="https://colab.research.google.com/github/Leonela180/Ejemplos-/blob/main/Ejercicios_dia1_Uipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy, libreria de ciencia de datos**

In [ ]:
import numpy as np
#pip install numpy

ARRAY DE 1 DIMENSION

In [ ]:
array_id=np.array([10,20,30])
print(array_id)

[10 20 30]


In [ ]:
array_id

array([10, 20, 30])

ARRAYS DE 2 DIMENSIONES

In [ ]:
array_2d=np.array([(10,20,30),(50,60,70)])
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

ARRAY DE 3 DIMENCIONES

In [ ]:
array_3d=np.array([(10.6,20,30),(40,50,60),(70,80,90)],dtype=float)
array_3d

array([[10.6, 20. , 30. ],
       [40. , 50. , 60. ],
       [70. , 80. , 90. ]])

ARRAY CON CEROS DE 3 FILAS Y 4 COLUMNAS

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


ARRAY DE UNOS CON 2 DIMENSIONES DE 4 FILAS 5 COLUMNAS

In [ ]:
np.ones((2,4,5)) # cantidad, fila, columna NP=MODULO

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAY CON INTERVALOS Y SALTOS

In [ ]:
np.arange(11,30,2) # del 11 al 30 de 2 en 2

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

**Practica hallar primos**

In [ ]:
np.arange(15,30)



array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

ARRAY CON INTERVALO Y DIVISIONES

In [ ]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAY CON VALORES DADOS


In [ ]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

ARRAY CON MATRIZ IDENTIDAD, DIAGONA DE UNOS


In [ ]:
1-np.eye((3))

array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

ARRAY VALORES ALEATORIOS 0-1

In [ ]:
np.random.random((4,4))

array([[0.7056941 , 0.16876494, 0.37044405, 0.04266858],
       [0.25886406, 0.72098159, 0.89546704, 0.66744405],
       [0.14148966, 0.86509824, 0.86713178, 0.99005594],
       [0.6620834 , 0.45422939, 0.84563487, 0.74662431]])

ARRAY DE NUMEROS VACION 4*3

In [ ]:
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

GRABAR Y CARGAR

In [ ]:
#GRABAR
np.save('mi_array_3d',array_3d)#se puede llamar a las variables anteriores

In [ ]:
#CARGAR
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[10.6, 20. , 30. ],
       [40. , 50. , 60. ],
       [70. , 80. , 90. ]])

Llamando al array de dos dimensiones

In [ ]:
#GRABAR
np.save('mi_array_3d',array_2d)

In [ ]:
#CARGAR
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[10, 20, 30],
       [50, 60, 70]])

GRABAR Y CARGAR FICHEROS DE TEXTO


In [ ]:
#GRABAR FICHERO DE TEXTO
np.savetxt('mi_array.txt',array_2d,delimiter=" ")

In [ ]:
#CARGAR DE FICHERO DE TEXTO
np.loadtxt('mi_array.txt')

array([[10., 20., 30.],
       [50., 60., 70.]])

# **DIA DOS DE CLASES------------------------------**

**TIPOS DE DATOS**

In [ ]:
#Enteros
np.int64

numpy.int64

In [ ]:
#Decimal, flotante
np.float64

numpy.float64

In [ ]:
# Complejos
np.complex64

numpy.complex64

In [ ]:
#Booleanos
np.bool_

numpy.bool

In [ ]:
#Objetos
np.object_

numpy.object_

In [ ]:
#Cadenas de texto
np.strings

<module 'numpy.strings' from '/usr/local/lib/python3.11/dist-packages/numpy/strings/__init__.py'>

In [ ]:
np.bytes_

numpy.bytes_

In [ ]:
np.unicode # formato srings saco este codigo

PROPIEDADES Y CARACTERISTICAS DE ENTORNOS

In [ ]:
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [ ]:
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

In [ ]:
array_2d.shape

(2, 3)

In [ ]:
#longitud
len(array_3d)#el mayor dato de cantidad

3

In [ ]:
#Numero de dimensiones
array_3d.ndim

2

In [97]:
array_5d = np.array([
    [[[(1,2,3,4,5),(4,5,6,5,4),(7,8,9,5,1,),(10,11,12,6,4),(13,14,15,5,4)]]],
   [[[(1,2,3,4,5),(4,5,6,5,4),(7,8,9,5,1,),(10,11,12,6,4),(13,14,15,5,4)]]],
    [[[(1,2,3,4,5),(4,5,6,5,4),(7,8,9,5,1,),(10,11,12,6,4),(13,14,15,5,4)]]],
    [[[(1,2,3,4,5),(4,5,6,5,4),(7,8,9,5,1,),(10,11,12,6,4),(13,14,15,5,4)]]],
    [[[(1,2,3,4,5),(4,5,6,5,4),(7,8,9,5,1,),(10,11,12,6,4),(13,14,15,5,4)]]]
])
array_5d

array([[[[[ 1,  2,  3,  4,  5],
          [ 4,  5,  6,  5,  4],
          [ 7,  8,  9,  5,  1],
          [10, 11, 12,  6,  4],
          [13, 14, 15,  5,  4]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 4,  5,  6,  5,  4],
          [ 7,  8,  9,  5,  1],
          [10, 11, 12,  6,  4],
          [13, 14, 15,  5,  4]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 4,  5,  6,  5,  4],
          [ 7,  8,  9,  5,  1],
          [10, 11, 12,  6,  4],
          [13, 14, 15,  5,  4]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 4,  5,  6,  5,  4],
          [ 7,  8,  9,  5,  1],
          [10, 11, 12,  6,  4],
          [13, 14, 15,  5,  4]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 4,  5,  6,  5,  4],
          [ 7,  8,  9,  5,  1],
          [10, 11, 12,  6,  4],
          [13, 14, 15,  5,  4]]]]])

In [98]:
array_5d.ndim

5

In [ ]:
#Tipos de datos
array_3d

In [87]:
array_3d

array([[10.6, 20. , 30. ],
       [40. , 50. , 60. ],
       [70. , 80. , 90. ]])

In [88]:
#Convertir de un tipo a otro tipo de dato
array_3d.astype(int)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

OPRERADORES MATEMÀTICOS

In [99]:
array_id

array([10, 20, 30])

In [100]:
#Array de ejemplo
array1=np.random.random((4,4))
array1

array([[0.09132214, 0.14317128, 0.19792759, 0.80723069],
       [0.96121284, 0.13490935, 0.02564495, 0.12091487],
       [0.74646779, 0.49932024, 0.49502625, 0.89116922],
       [0.7690849 , 0.94853862, 0.0051304 , 0.99042886]])

In [101]:
array2=np.random.random((4,4))
array2

array([[0.48977795, 0.12116021, 0.68443702, 0.2614688 ],
       [0.09268029, 0.1487432 , 0.03816408, 0.76078102],
       [0.14477004, 0.17701113, 0.68097379, 0.44390368],
       [0.22264864, 0.68722122, 0.28797486, 0.79391817]])

In [102]:
array3=np.random.random((4,4))
array3

array([[0.27238741, 0.27922333, 0.92003056, 0.61006634],
       [0.89827987, 0.48027014, 0.70441835, 0.61583866],
       [0.84421653, 0.00119924, 0.34114219, 0.49458726],
       [0.87541466, 0.99253661, 0.13971691, 0.53079953]])

In [103]:
#SUMA--- primera forma---
array4=(array1+array2+array3)
array4

array([[0.8534875 , 0.54355482, 1.80239516, 1.67876582],
       [1.95217299, 0.76392269, 0.76822738, 1.49753455],
       [1.73545435, 0.67753062, 1.51714224, 1.82966016],
       [1.86714821, 2.62829645, 0.43282217, 2.31514656]])

In [104]:
#segunda forma
array4=np.add(array1,array2,array3)
array4

array([[0.58110009, 0.26433149, 0.8823646 , 1.06869949],
       [1.05389312, 0.28365255, 0.06380902, 0.88169589],
       [0.89123782, 0.67633138, 1.17600005, 1.3350729 ],
       [0.99173355, 1.63575984, 0.29310526, 1.78434703]])

In [105]:
#RESTA
array4= array1-array2-array3
array4

array([[-0.97955589, -0.24232042, -1.36887403, -0.52293759],
       [-0.18536057, -0.29748641, -0.07632815, -1.52156205],
       [-0.28954007, -0.35402227, -1.36194759, -0.88780735],
       [-0.44529729, -1.37444244, -0.57594972, -1.58783635]])

In [107]:
#resta--segunda forma-
array4=np.subtract(array1,array2,array3)
array4

array([[-0.3984558 ,  0.02201107, -0.48650943,  0.54576189],
       [ 0.86853255, -0.01383386, -0.01251913, -0.63986615],
       [ 0.60169775,  0.32230911, -0.18594754,  0.44726555],
       [ 0.54643626,  0.2613174 , -0.28284446,  0.19651068]])

In [106]:
#MULTIPPLICACION
array4=np.multiply(array1,array2,array3)
array4

array([[0.04472757, 0.01734666, 0.13546897, 0.21106564],
       [0.08908548, 0.02006685, 0.00097872, 0.09198974],
       [0.10806617, 0.08838524, 0.33709991, 0.39559329],
       [0.17123571, 0.65185586, 0.00147743, 0.78631947]])

In [108]:
#DIVIDIR
array4=np.divide(array1,array2)
array4

array([[ 0.18645622,  1.18166914,  0.28918305,  3.08729263],
       [10.37127611,  0.90699503,  0.6719657 ,  0.15893518],
       [ 5.15623125,  2.8208409 ,  0.72693877,  2.00757342],
       [ 3.45425372,  1.38025223,  0.01781545,  1.24752007]])

In [109]:
# EXPONENTES
np.exp(array1)

array([[1.0956219 , 1.15392743, 1.21887413, 2.24169144],
       [2.61486596, 1.14443303, 1.02597661, 1.12852884],
       [2.10953551, 1.64760092, 1.64054131, 2.43797852],
       [2.15779076, 2.58193371, 1.00514358, 2.69238887]])

In [110]:
# OPERADORES TRIGONOMETRICO (SEN-COS)
np.sin(array1)


array([[0.09119526, 0.14268266, 0.1966378 , 0.72237496],
       [0.81988655, 0.13450048, 0.02564214, 0.12062045],
       [0.67905003, 0.47882888, 0.47505475, 0.77780714],
       [0.69547799, 0.81256457, 0.00513038, 0.83626121]])

In [111]:
np.cos(array1)

array([[0.99583303, 0.98976849, 0.9804762 , 0.69150156],
       [0.57252602, 0.99091353, 0.99967119, 0.9926987 ],
       [0.73409199, 0.87790825, 0.87995624, 0.62850303],
       [0.7185474 , 0.58287118, 0.99998684, 0.54833128]])

In [112]:
#LOGARITMO
np.log(array1)

array([[-2.39336199, -1.94371361, -1.61985405, -0.21414579],
       [-0.03955942, -2.00315224, -3.66340863, -2.11266855],
       [-0.29240281, -0.69450762, -0.70314448, -0.11522095],
       [-0.26255391, -0.05283278, -5.27257135, -0.00961724]])

*COMPARACIONES ENTRE MATRICES*

In [113]:
# == -> comparar
array1==array2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [114]:
# Menor
array1

array([[0.09132214, 0.14317128, 0.19792759, 0.80723069],
       [0.96121284, 0.13490935, 0.02564495, 0.12091487],
       [0.74646779, 0.49932024, 0.49502625, 0.89116922],
       [0.7690849 , 0.94853862, 0.0051304 , 0.99042886]])

In [115]:
array1<0.5

array([[ True,  True,  True, False],
       [False,  True,  True,  True],
       [False,  True,  True, False],
       [False, False,  True, False]])

In [116]:
array1>0.5

array([[False, False, False,  True],
       [ True, False, False, False],
       [ True, False, False,  True],
       [ True,  True, False,  True]])

In [117]:
# Menor igual o mayor igual
array2

array([[0.48977795, 0.12116021, 0.68443702, 0.2614688 ],
       [0.09268029, 0.1487432 , 0.03816408, 0.76078102],
       [0.14477004, 0.17701113, 0.68097379, 0.44390368],
       [0.22264864, 0.68722122, 0.28797486, 0.79391817]])

In [119]:
array2 >= 0.4

array([[ True, False,  True, False],
       [False, False, False,  True],
       [False, False,  True,  True],
       [False,  True, False,  True]])

*ESTADISTICAS Y FUNCIONES*

In [124]:
array6= np.random.random((5,5))
array6

array([[0.10495972, 0.72160517, 0.886103  , 0.02126262, 0.22117065],
       [0.2319182 , 0.6713706 , 0.2112826 , 0.90670394, 0.26005394],
       [0.36252855, 0.6401319 , 0.44881581, 0.8696736 , 0.85952104],
       [0.31471463, 0.17443063, 0.27172838, 0.51557749, 0.07292556],
       [0.56630918, 0.87001683, 0.19510255, 0.04970869, 0.65674733]])

In [126]:
# suma de elementos-- primera forma
suma_total=np.sum(array6)
suma_total

np.float64(11.104362574831425)

In [127]:
#segunda forma
sumatotal=array6.sum()
sumatotal

np.float64(11.104362574831425)

In [128]:
#valor minimo y maximo
array6.min() # max

np.float64(0.021262622727902136)

In [129]:
# valor min o max por fila o columna
array6.max(axis=0) #axis 0 es columa y axis=1 filas

array([0.56630918, 0.87001683, 0.886103  , 0.90670394, 0.85952104])

In [130]:
#fila acumulada
array6.cumsum(axis=1)

array([[0.10495972, 0.82656488, 1.71266789, 1.73393051, 1.95510116],
       [0.2319182 , 0.90328879, 1.11457139, 2.02127533, 2.28132927],
       [0.36252855, 1.00266045, 1.45147626, 2.32114985, 3.1806709 ],
       [0.31471463, 0.48914525, 0.76087363, 1.27645112, 1.34937668],
       [0.56630918, 1.43632601, 1.63142856, 1.68113725, 2.33788457]])

In [131]:
#media arimetica
np.mean(array6)

np.float64(0.444174502993257)

In [132]:
#mediana
np.median(array6)

np.float64(0.3625285490854516)

In [133]:
#desviacion estandar
np.std(array6)

np.float64(0.2922041884094334)