<a href="https://colab.research.google.com/github/Leonela180/Ejemplos-/blob/main/Ejercicios_dia1_Uipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy, libreria de ciencia de datos**

In [ ]:
import numpy as np
#pip install numpy

ARRAY DE 1 DIMENSION

In [ ]:
array_id=np.array([10,20,30])
print(array_id)

[10 20 30]


In [ ]:
array_id

array([10, 20, 30])

ARRAYS DE 2 DIMENSIONES

In [ ]:
array_2d=np.array([(10,20,30),(50,60,70)])
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

ARRAY DE 3 DIMENCIONES

In [ ]:
array_3d=np.array([(10.6,20,30),(40,50,60),(70,80,90)],dtype=float)
array_3d

array([[10.6, 20. , 30. ],
       [40. , 50. , 60. ],
       [70. , 80. , 90. ]])

ARRAY CON CEROS DE 3 FILAS Y 4 COLUMNAS

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


ARRAY DE UNOS CON 2 DIMENSIONES DE 4 FILAS 5 COLUMNAS

In [ ]:
np.ones((2,4,5)) # cantidad, fila, columna NP=MODULO

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAY CON INTERVALOS Y SALTOS

In [ ]:
np.arange(11,30,2) # del 11 al 30 de 2 en 2

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

**Practica hallar primos**

In [ ]:
np.arange(15,30)



array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

ARRAY CON INTERVALO Y DIVISIONES

In [ ]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAY CON VALORES DADOS


In [ ]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

ARRAY CON MATRIZ IDENTIDAD, DIAGONA DE UNOS


In [ ]:
1-np.eye((3))

array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

ARRAY VALORES ALEATORIOS 0-1

In [ ]:
np.random.random((4,4))

array([[9.23550857e-01, 3.51736606e-01, 9.93089447e-01, 1.66232346e-01],
       [3.65706114e-01, 9.97275744e-01, 5.22838683e-01, 4.85089957e-01],
       [4.64193365e-01, 5.60819537e-01, 8.83073387e-01, 8.92530502e-04],
       [2.70039409e-01, 2.26959544e-01, 9.44881809e-01, 2.25140289e-01]])

ARRAY DE NUMEROS VACION 4*3

In [ ]:
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

GRABAR Y CARGAR

In [ ]:
#GRABAR
np.save('mi_array_3d',array_3d)#se puede llamar a las variables anteriores

In [ ]:
#CARGAR
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[10.6, 20. , 30. ],
       [40. , 50. , 60. ],
       [70. , 80. , 90. ]])

Llamando al array de dos dimensiones

In [ ]:
#GRABAR
np.save('mi_array_3d',array_2d)

In [ ]:
#CARGAR
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[10, 20, 30],
       [50, 60, 70]])

GRABAR Y CARGAR FICHEROS DE TEXTO


In [ ]:
#GRABAR FICHERO DE TEXTO
np.savetxt('mi_array.txt',array_2d,delimiter=" ")

In [ ]:
#CARGAR DE FICHERO DE TEXTO
np.loadtxt('mi_array.txt')

array([[10., 20., 30.],
       [50., 60., 70.]])

**EJERCICIOS PROPUESTOS -- CLASE 1 -- **

In [82]:
#ejercicio 1
cursos=np.array(["Matemáticas","Física","Química","Historia","Lengua"])
print(cursos)

['Matemáticas' 'Física' 'Química' 'Historia' 'Lengua']


In [93]:
#ejercicio 2
cursos=np.array(["Matemáticas","Física","Química","Historia","Lengua"])

print("Yo estudio ",cursos[0],)
print("Yo estudio ",cursos[1],)
print("Yo estudio ",cursos[2],)
print("Yo estudio ",cursos[3],)
print("Yo estudio ",cursos[4],)


Yo estudio  Matemáticas
Yo estudio  Física
Yo estudio  Química
Yo estudio  Historia
Yo estudio  Lengua


In [103]:
#ejercicio 3
cursos=np.array(["Matemáticas","Física","Química","Historia","Lengua"])

uno = input("Que nota saco en "+cursos[0]+": ")
dos = input("Que nota saco en "+cursos[1]+": ")
tres = input("Que nota saco en "+cursos[2]+": ")
cuatro = input("Que nota saco en "+cursos[3]+": ")
cinco = input("Que nota saco en "+cursos[4]+": ")
print("------------------------------------")
print("En "+cursos[0]+" has sacado "+uno)
print("En "+cursos[1]+" has sacado "+dos)
print("En "+cursos[2]+" has sacado "+tres)
print("En "+cursos[3]+" has sacado "+cuatro)
print("En "+cursos[4]+" has sacado "+cinco)



Que nota saco en Matemáticas: 14
Que nota saco en Física: 16
Que nota saco en Química: 2
Que nota saco en Historia: 4
Que nota saco en Lengua: 5
En Matemáticas has sacado 14
En Física has sacado 16
En Química has sacado 2
En Historia has sacado 4
En Lengua has sacado 5


In [122]:
#ejercicio 4

numeros = []

for i in range(3):  # Suponiendo 6 números ganadores
    numero =(input(f"Introduce el número ganador {i+1}: "))
    numeros.append(numero)

    array = np.array(numeros)
    ordenena = np.sort(array)

numeros.sort()
print("Números ganadores ordenados:", numeros)


Introduce el número ganador 1: 15
Introduce el número ganador 2: 6
Introduce el número ganador 3: 1
Números ganadores ordenados: ['1', '15', '6']
