<a href="https://colab.research.google.com/github/Leonela180/Ejemplos-/blob/main/Ejercicios_dia1_Uipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy, libreria de ciencia de datos**

In [2]:
import numpy as np
#pip install numpy

ARRAY DE 1 DIMENSION

In [3]:
array_id=np.array([10,20,30])
print(array_id)

[10 20 30]


In [4]:
array_id

array([10, 20, 30])

ARRAYS DE 2 DIMENSIONES

In [5]:
array_2d=np.array([(10,20,30),(50,60,70)])
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

ARRAY DE 3 DIMENCIONES

In [8]:
array_3d=np.array([(10.6,20,30),(40,50,60),(70,80,90)],dtype=float)
array_3d

array([[10.6, 20. , 30. ],
       [40. , 50. , 60. ],
       [70. , 80. , 90. ]])

ARRAY CON CEROS DE 3 FILAS Y 4 COLUMNAS

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


ARRAY DE UNOS CON 2 DIMENSIONES DE 4 FILAS 5 COLUMNAS

In [12]:
np.ones((2,4,5)) # cantidad, fila, columna NP=MODULO

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAY CON INTERVALOS Y SALTOS

In [13]:
np.arange(11,30,2) # del 11 al 30 de 2 en 2

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

**Practica hallar primos**

In [15]:
np.arange(15,30)


array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

ARRAY CON INTERVALO Y DIVISIONES

In [16]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAY CON VALORES DADOS


In [17]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

ARRAY CON MATRIZ IDENTIDAD, DIAGONA DE UNOS


In [37]:
1-np.eye((3))

array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

ARRAY VALORS ALEATORIOS 0-1

In [34]:
np.random.random((4,4))

array([[9.23550857e-01, 3.51736606e-01, 9.93089447e-01, 1.66232346e-01],
       [3.65706114e-01, 9.97275744e-01, 5.22838683e-01, 4.85089957e-01],
       [4.64193365e-01, 5.60819537e-01, 8.83073387e-01, 8.92530502e-04],
       [2.70039409e-01, 2.26959544e-01, 9.44881809e-01, 2.25140289e-01]])

ARRAY DE NUMEROS VACION 4*3

In [ ]:
np.empty((4,3))